Repository DPA-SJSU/Degree-Planning-Assistant, pull requests merged in 2020-03, with the labels that each got.

#27 021: courses-taken
  client/src/app/app-routing.module.ts
  client/src/app/app.component.html
  client/src/app/app.module.ts
  client/src/app/course.service.spec.ts
  client/src/app/course.service.ts
  client/src/app/error-handler.service.ts
  client/src/app/footer/footer.component.css
  client/src/app/footer/footer.component.html
  client/src/app/landing/landing.component.css
  client/src/app/landing/landing.component.html
  client/src/app/login/login.component.html
  client/src/app/navbar/navbar.component.css
  client/src/app/navbar/navbar.component.html
  client/src/app/navbar/navbar.component.ts
  client/src/app/popup/popup.component.css
  client/src/app/popup/popup.component.html
  client/src/app/popup/popup.component.spec.ts
  client/src/app/popup/popup.component.ts
  client/src/app/registration/registration.component.html
  client/src/app/registration/registration.component.ts
  client/src/app/s-courses-taken/s-courses-taken.component.css
  client/src/app/s-courses-taken/s-courses-taken.component.html
  client/src/app/s-courses-taken/s-courses-taken.component.spec.ts
  client/src/app/s-courses-taken/s-courses-taken.component.ts
  client/src/app/user.service.ts
  client/src/assets/hamburger-menu.png
  client/src/styles.css
  old server/database/dpa-schema.sql
  old server/database/init.sql
  server/controller/constant.js
  server/controller/course.controller.js
  server/controller/program.controller.js
  server/controller/semester.controller.js
  server/controller/user.controller.js
  server/controller/validation/course.validation.js
  server/controller/validation/program.validation.js
  server/controller/validation/user.validation.js
  server/database/schemas/program.schema.js
  server/database/schemas/user.schema.js
Labels: Frontend, sprint-5

#29 022 student view course details
  client/src/app/app.module.ts
  client/src/app/course.service.spec.ts
  client/src/app/course.service.ts
  client/src/app/modal/modal.component.css
  client/src/app/modal/modal.component.html
  client/src/app/modal/modal.component.spec.ts
  client/src/app/modal/modal.component.ts
  client/src/app/popup/popup.component.css
  client/src/app/popup/popup.component.html
  client/src/app/popup/popup.component.ts
  client/src/app/s-courses-taken/s-courses-taken.component.html
  client/src/app/s-courses-taken/s-courses-taken.component.ts
  client/src/app/user.service.ts
  client/src/styles.css
  server/controller/user.controller.js
Labels: Frontend, UI, feature, sprint-6

#25 [015-Backend]: Adding semesters with courses taken (VIA FILE UPLOAD)
  .gitignore
  docs/Server Docs/userAPI.MD
  old server/.babelrc
  old server/.eslintrc.json
  old server/.gcloudignore
  old server/.gitignore
  old server/App.js
  old server/README.md
  old server/app.yaml
  old server/controller/constant.js
  old server/controller/index.js
  old server/controller/user.controller.js
  old server/database/constant.js
  old server/database/dpa-schema.sql
  old server/database/drop.sql
  old server/database/init.sql
  old server/package.json
  old server/store/config.js
  old server/store/passport.js
  old server/store/utils.js
  server/.gitignore
  server/App.js
  server/controller/course.controller.js
  server/controller/index.js
  server/controller/program.controller.js
  server/controller/semester.controller.js
  server/controller/textScan.controller.js
  server/controller/user.controller.js
  server/controller/validation/course.validation.js
  server/controller/validation/program.validation.js
  server/controller/validation/semester.validation.js
  server/controller/validation/user.validation.js
  server/database/models/index.js
  server/database/mongo.js
  server/database/schemas/course.schema.js
  server/database/schemas/user.schema.js
  server/package.json
  server/store/Scanning/cloudOCR.js
  server/store/errorMapping.js
  server/store/utils.js
Labels: Backend, feature, sprint-4, sprint-5

#17 012: Degree PLAN Schema and basic API (Backend)
  server/App.js
  server/controller/constant.js
  server/controller/course.controller.js
  server/controller/index.js
  server/controller/plan.controller.js
  server/controller/semester.controller.js
  server/controller/textScan.controller.js
  server/controller/user.controller.js
  server/controller/validation/plan.validation.js
  server/controller/validation/user.validation.js
  server/database/models/index.js
  server/database/models/plan.model.js
  server/database/schemas/plan.schema.js
  server/database/schemas/semester.schema.js
  server/database/schemas/user.schema.js
  server/store/Scanning/cloudOCR.js
Labels: Backend, sprint-4, sprint-5, sprint-6

#35 027: User Dashboard (Frontend)
  client/src/app/app-routing.module.ts
  client/src/app/app.module.ts
  client/src/app/auth.guard.ts
  client/src/app/login/login.component.ts
  client/src/app/navbar/navbar.component.html
  client/src/app/s-courses-taken/s-courses-taken.component.ts
  client/src/app/s-dashboard/s-dashboard.component.css
  client/src/app/s-dashboard/s-dashboard.component.html
  client/src/app/s-dashboard/s-dashboard.component.spec.ts
  client/src/app/s-dashboard/s-dashboard.component.ts
  client/src/app/user.service.ts
  server/controller/user.controller.js
  server/controller/validation/user.validation.js
Labels: sprint-7

#28 020 & 028: Display and Edit Student Profile (Frontend)
  client/src/app/app-routing.module.ts
  client/src/app/app.module.ts
  client/src/app/auth.guard.ts
  client/src/app/error-handler.service.ts
  client/src/app/s-courses-taken/s-courses-taken.component.css
  client/src/app/s-courses-taken/s-courses-taken.component.html
  client/src/app/s-courses-taken/s-courses-taken.component.ts
  client/src/app/s-dashboard/s-dashboard.component.css
  client/src/app/s-dashboard/s-dashboard.component.html
  client/src/app/s-profile-dash/s-profile-dash.component.css
  client/src/app/s-profile-dash/s-profile-dash.component.html
  client/src/app/s-profile-dash/s-profile-dash.component.spec.ts
  client/src/app/s-profile-dash/s-profile-dash.component.ts
  client/src/app/s-profile/s-profile.component.css
  client/src/app/s-profile/s-profile.component.html
  client/src/app/s-profile/s-profile.component.spec.ts
  client/src/app/s-profile/s-profile.component.ts
  client/src/app/user.service.ts
  client/src/assets/bio_16.png
  client/src/assets/degree_program.png
  client/src/assets/email_16.png
  client/src/assets/grad_date_16.png
  client/src/assets/major_16.png
  client/src/assets/profile-pic-92.png
  client/src/assets/school_16.png
  client/src/styles.css
  server/controller/user.controller.js
  server/controller/validation/user.validation.js
  server/database/schemas/user.schema.js
Labels: sprint-5, sprint-6
