Repository DPA-SJSU/Degree-Planning-Assistant, pull requests merged in 2020-05, with the labels that each got.

#61 23: Save degree plan (Frontend)
  client/src/app/plan.service.ts
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.html
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.ts
  client/src/app/s-degree-plan/s-degree-plan.component.html
  client/src/app/s-degree-plan/s-degree-plan.component.ts
Labels: Frontend

#69 [finish impl] Create Program after creating requirements
  server/controller/constant.js
  server/controller/plan.controller.js
  server/controller/requirement.controller.js
Labels: Backend, enhancement

#78 [finish impl] [Feature] Setup Google SSO
  server/App.js
  server/controller/user.controller.js
  server/database/schemas/user.schema.js
  server/package.json
  server/store/passport.js
Labels: Backend, complete, enhancement, feature

#79 [Feature] Build our own mailing services using Gmail, and GCloud Oauth2 Services
  server/controller/mailing.controller.js
  server/database/models/index.js
  server/database/models/subscriber.model.js
  server/database/schemas/subscriber.schema.js
  server/package.json
  server/store/mailing.js
  server/templates/confirmedEmail.ejs
  server/templates/forgotPassword.ejs
  server/templates/registerConfirmation.ejs
  server/templates/resetPassword.ejs
  server/templates/subscribe.ejs
Labels: Backend, feature

#67 [finish impl] Setup Very first Unit Testing"
  server/App.js
  server/package.json
  server/test/unit/user.unit.js
Labels: Backend, complete, feature, testing
