Repository DPA-SJSU/Degree-Planning-Assistant, pull requests merged in 2020-02, with the labels that each got.

#16 009-Course API
  server/App.js
  server/controller/constant.js
  server/controller/course.controller.js
  server/controller/index.js
  server/controller/validation/course.validation.js
  server/database/models/course.model.js
  server/database/models/index.js
  server/database/schemas/course.schema.js
Labels: Backend, feature, sprint-4

#21 011-Semester: Semester API
  server/.babelrc
  server/App.js
  server/controller/constant.js
  server/controller/course.controller.js
  server/controller/index.js
  server/controller/semester.controller.js
  server/controller/user.controller.js
  server/controller/validation/semester.validation.js
  server/database/models/index.js
  server/database/models/semester.model.js
  server/database/schemas/semester.schema.js
  server/database/schemas/user.schema.js
  server/package.json
  server/store/config.js
  server/store/passport.js
  server/store/utils.js
Labels: Backend, sprint-4

#22 013: Degree PROGRAM Schema and Basic API (Backend)
  package.json
  server/App.js
  server/controller/constant.js
  server/controller/index.js
  server/controller/program.controller.js
  server/controller/user.controller.js
  server/controller/validation/program.validation.js
  server/controller/validation/user.validation.js
  server/database/models/index.js
  server/database/models/program.model.js
  server/database/schemas/program.schema.js
  server/package.json
Labels: Backend, sprint-4, sprint-5

#23 019: Edit Profile (Backend)
  server/controller/constant.js
  server/controller/course.controller.js
  server/controller/user.controller.js
  server/controller/validation/user.validation.js
  server/database/schemas/user.schema.js
Labels: Backend, sprint-5
