Repository DPA-SJSU/Degree-Planning-Assistant, pull requests merged in 2020-04, with the labels that each got.

#30 [024-backend]: Enhance Text Scanning
  server/App.js
  server/app.yaml
  server/controller/SE-program.json
  server/controller/constant.js
  server/controller/course.controller.js
  server/controller/index.js
  server/controller/plan.controller.js
  server/controller/program.controller.js
  server/controller/requirement.controller.js
  server/controller/semester.controller.js
  server/controller/textScan.controller.js
  server/controller/user.controller.js
  server/controller/validation/program.validation.js
  server/controller/validation/semester.validation.js
  server/database/models/index.js
  server/database/models/requirement.model.js
  server/database/schemas/course.schema.js
  server/database/schemas/plan.schema.js
  server/database/schemas/program.schema.js
  server/database/schemas/requirement.schema.js
  server/database/schemas/user.schema.js
  server/package.json
  server/response.json
  server/store/Scanning/cloudOCR.js
  server/store/utils.js
  server/uploads/3be7e90ba99d3d792e845e880470076f
  server/uploads/51e946b2b965578c031fe5646fe9cc64
  server/uploads/b8bd7ce1c30bbcc8e7be64a096d5271a
  server/uploads/c2b0dcbbdfd2404a4e7295ad96799842
  server/uploads/faa6eaf6b8c565dbc42f0a83fb95a609
Labels: Backend, enhancement, sprint-7

#38 031: upload transcript
  client/src/app/app.module.ts
  client/src/app/s-courses-taken/s-courses-taken.component.html
  client/src/app/s-courses-taken/s-courses-taken.component.ts
  client/src/app/s-dashboard/s-dashboard.component.html
  client/src/app/s-dashboard/s-dashboard.component.ts
  client/src/app/s-profile-dash/s-profile-dash.component.html
  client/src/app/s-profile-dash/s-profile-dash.component.ts
  client/src/app/user.service.ts
  server/App.js
  server/package.json
  server/store/Scanning/cloudOCR.js
Labels: sprint-8

#34 023: Display Degree Plan (Frontend)
  client/src/app/app-routing.module.ts
  client/src/app/app.module.ts
  client/src/app/auth.guard.ts
  client/src/app/modal/modal.component.html
  client/src/app/plan.service.spec.ts
  client/src/app/plan.service.ts
  client/src/app/s-courses-taken/s-courses-taken.component.html
  client/src/app/s-dashboard/s-dashboard.component.html
  client/src/app/s-degree-plan/s-degree-plan.component.css
  client/src/app/s-degree-plan/s-degree-plan.component.html
  client/src/app/s-degree-plan/s-degree-plan.component.spec.ts
  client/src/app/s-degree-plan/s-degree-plan.component.ts
  client/src/app/s-profile/s-profile.component.html
  client/src/app/user.service.ts
  client/src/assets/add-48.png
  client/src/assets/difficulty-16.png
  client/src/assets/impaction-16.png
  client/src/styles.css
  server/.gitignore
  server/controller/user.controller.js
  server/package.json
Labels: sprint-5

#36 026: Manually add courses
  client/src/app/app.module.ts
  client/src/app/course.service.spec.ts
  client/src/app/course.service.ts
  client/src/app/modal/modal.component.html
  client/src/app/modal/modal.component.ts
  client/src/app/s-courses-taken/s-courses-taken.component.css
  client/src/app/s-courses-taken/s-courses-taken.component.html
  client/src/app/s-courses-taken/s-courses-taken.component.ts
  client/src/app/user.service.ts
  server/controller/semester.controller.js
  server/controller/user.controller.js
  server/controller/validation/user.validation.js
Labels: sprint-7

#40 024: Add Remaining Requirements after scanning transcript
  .gitignore
  server/app.yaml
  server/controller/constant.js
  server/controller/course.controller.js
  server/controller/plan.controller.js
  server/controller/program.controller.js
  server/controller/requirement.controller.js
  server/controller/semester.controller.js
  server/controller/textScan.controller.js
  server/controller/user.controller.js
  server/controller/validation/requirement.validation.js
  server/database/schemas/plan.schema.js
  server/package.json
  server/response.json
  server/store/Scanning/cloudOCR.js
  server/store/Scanning/sampleData/CloudOcrResponse.js
  server/store/Scanning/sampleData/SE-program.json
  server/store/Scanning/sampleData/scanResult.js
  server/store/utils.js
  server/uploads/3be7e90ba99d3d792e845e880470076f
  server/uploads/51e946b2b965578c031fe5646fe9cc64
  server/uploads/b8bd7ce1c30bbcc8e7be64a096d5271a
  server/uploads/c2b0dcbbdfd2404a4e7295ad96799842
  server/uploads/faa6eaf6b8c565dbc42f0a83fb95a609
Labels: Backend, complete, sprint-8

#43 Bug Fix: API for fetching courses using school and code no longer working
  client/src/app/course.service.ts
  server/controller/constant.js
  server/controller/course.controller.js
  server/controller/validation/course.validation.js
Labels: bug

#44 Bug Fix: Unhandled Error in GET Program using id, school, and/or major
  server/controller/program.controller.js
Labels: bug

#49 [Hotfix] Update scripts and config for dev & prod
  server/app.yaml
  server/package.json
  server/store/config.js
Labels: Backend, enhancement

#50 [finish impl] Update Requirements & course Info
  server/controller/course.controller.js
  server/controller/requirement.controller.js
  server/database/schemas/course.schema.js
  server/store/Scanning/sampleData/SE-program.json
  server/store/Scanning/sampleData/courseInfo.json
  server/store/utils.js
Labels: Backend, feature, sprint-9

#51 [finish impl] Improve OCR scanning accuracy and speed
  server/controller/textScan.controller.js
  server/store/Scanning/cloudOCR.js
  server/store/Scanning/sampleData/CloudOcrResponse.js
  server/store/Scanning/sampleData/scanResult.js
  server/store/utils.js
Labels: Backend, enhancement, sprint-9

#52 023: Edit Plan markup
  client/src/app/app-routing.module.ts
  client/src/app/app.module.ts
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.css
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.html
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.spec.ts
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.ts
  client/src/assets/delete-32.png
Labels: Frontend, sprint-9

#55 023: edit degree plan with user data
  client/src/app/plan.service.ts
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.html
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.ts
  client/src/app/s-degree-plan/s-degree-plan.component.html
  client/src/app/s-degree-plan/s-degree-plan.component.ts
Labels: sprint-9

#56 Editing Plan Frontend: Adding new semesters
  client/src/app/plan.service.ts
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.html
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.ts
Labels: Frontend

#57 023: Edit Plan (Frontend); Delete Semesters. Drag/drop course chips
  client/src/app/plan.service.ts
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.html
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.ts
Labels: Frontend

#58 023: Edit Degree Plan; Populating the course list and removing courses from semesters
  client/src/app/error-handler.service.ts
  client/src/app/plan.service.ts
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.css
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.html
  client/src/app/s-degree-plan-editor/s-degree-plan-editor.component.ts
  server/package.json
Labels: Frontend

#48 [finish impl] Update remaining Requirement after OCR
  .eslintrc
  app.yaml
  package.json
  server/controller/constant.js
  server/controller/course.controller.js
  server/controller/plan.controller.js
  server/controller/requirement.controller.js
  server/controller/semester.controller.js
  server/controller/textScan.controller.js
  server/database/schemas/course.schema.js
  server/database/schemas/plan.schema.js
  server/database/schemas/program.schema.js
  server/database/schemas/requirement.schema.js
  server/database/schemas/semester.schema.js
  server/database/schemas/user.schema.js
  server/store/Scanning/sampleData/CloudOcrResponse.js
  server/store/Scanning/sampleData/SE-program.json
  server/store/Scanning/sampleData/planSample.json
  server/store/Scanning/sampleData/scanResult.js
  server/store/Scanning/sampleData/scanResult.json
  server/store/utils.js
Labels: Backend, enhancement, sprint-9

#60 [bugfix] Find course that is followed by keyword "https"
  server/store/Scanning/cloudOCR.js
Labels: Backend, bug

#64 [bugfix] Scan smaller transcripts
  server/controller/textScan.controller.js
  server/store/Scanning/cloudOCR.js
Labels: Backend, bug

#65 038: refresh student portal components on new user
  client/src/app/plan.service.ts
  client/src/app/s-dashboard/s-dashboard.component.html
  client/src/app/s-degree-plan/s-degree-plan.component.html
  client/src/app/s-degree-plan/s-degree-plan.component.ts
  client/src/styles.css
Labels: sprint-10
